export const constructorImages = {
    aston_martin: require('./assets/images/constructors/aston_martin.png'),
    ferrari: require('./assets/images/constructors/ferrari.png'),
    mercedes: require('./assets/images/constructors/mercedes.png'),
    alpine: require('./assets/images/constructors/alpine.png'),
    haas: require('./assets/images/constructors/haas.png'),
    mclaren: require('./assets/images/constructors/mclaren.png'),
    rb: require('./assets/images/constructors/rb.png'),
    red_bull: require('./assets/images/constructors/red_bull.png'),
    sauber: require('./assets/images/constructors/sauber.png'),
    williams: require('./assets/images/constructors/williams.png'),
};

export const constructorColor = {
    aston_martin: '#229971',
    ferrari: '#E80020',
    mercedes: '#27F4d2',
    alpine: '#0093CC',
    haas: '#B6BDBD',
    mclaren: '#FF8000',
    rb: '#6692FF',
    red_bull: '#3671C6',
    sauber: '#52E252',
    williams: '#64C4FF',
};

export const circuitFlags = {
    bahrain: require('./assets/images/flags/bahrain-flag.png'),
    jeddah: require('./assets/images/flags/jeddah-flag.png'),
    albert_park: require('./assets/images/flags/albert_park-flag.png'),
    suzuka: require('./assets/images/flags/suzuka-flag.png'),
    shanghai: require('./assets/images/flags/shanghai-flag.png'),
    miami: require('./assets/images/flags/miami-flag.png'),
    imola: require('./assets/images/flags/imola-flag.png'),
    monaco: require('./assets/images/flags/monaco-flag.png'),
    villeneuve: require('./assets/images/flags/villeneuve-flag.png'),
    catalunya: require('./assets/images/flags/catalunya-flag.png'),
    red_bull_ring: require('./assets/images/flags/red_bull_ring-flag.png'),
    silverstone: require('./assets/images/flags/silverstone-flag.png'),
    hungaroring: require('./assets/images/flags/hungaroring-flag.png'),
    spa: require('./assets/images/flags/spa-flag.png'),
    zandvoort: require('./assets/images/flags/zandvoort-flag.png'),
    monza: require('./assets/images/flags/monza-flag.png'),
    baku: require('./assets/images/flags/baku-flag.png'),
    marina_bay: require('./assets/images/flags/marina_bay-flag.png'),
    americas: require('./assets/images/flags/americas-flag.png'),
    rodriguez: require('./assets/images/flags/rodriguez-flag.png'),
    interlagos: require('./assets/images/flags/interlagos-flag.png'),
    vegas: require('./assets/images/flags/vegas-flag.png'),
    losail: require('./assets/images/flags/losail-flag.png'),
    yas_marina: require('./assets/images/flags/yas_marina-flag.png'),
};

export const circuitImages = {
    bahrain: require('./assets/images/circuits/Bahrain_Circuit.png'),
    jeddah: require('./assets/images/circuits/Saudi_Arabia_Circuit.png'),
    albert_park: require('./assets/images/circuits/Australia_Circuit.png'),
    suzuka: require('./assets/images/circuits/Japan_Circuit.png'),
    shanghai: require('./assets/images/circuits/China_Circuit.png'),
    miami: require('./assets/images/circuits/Miami_Circuit.png'),
    imola: require('./assets/images/circuits/Emilia_Romagna_Circuit.png'),
    monaco: require('./assets/images/circuits/Monoco_Circuit.png'),
    villeneuve: require('./assets/images/circuits/Canada_Circuit.png'),
    catalunya: require('./assets/images/circuits/Spain_Circuit.png'),
    red_bull_ring: require('./assets/images/circuits/Austria_Circuit.png'),
    silverstone: require('./assets/images/circuits/Great_Britain_Circuit.png'),
    hungaroring: require('./assets/images/circuits/Hungary_Circuit.png'),
    spa: require('./assets/images/circuits/Belgium_Circuit.png'),
    zandvoort: require('./assets/images/circuits/Netherlands_Circuit.png'),
    monza: require('./assets/images/circuits/Italy_Circuit.png'),
    baku: require('./assets/images/circuits/Baku_Circuit.png'),
    marina_bay: require('./assets/images/circuits/Singapore_Circuit.png'),
    americas: require('./assets/images/circuits/USA_Circuit.png'),
    rodriguez: require('./assets/images/circuits/Mexico_Circuit.png'),
    interlagos: require('./assets/images/circuits/Brazil_Circuit.png'),
    vegas: require('./assets/images/circuits/Las_Vegas_Circuit.png'),
    losail: require('./assets/images/circuits/Qatar_Circuit.png'),
    yas_marina: require('./assets/images/circuits/Abu_Dhabi_Circuit.png'),
};

export const DriverImages = {
    albon: require('./assets/images/drivers/albon.png'),
    alonso: require('./assets/images/drivers/alonso.png'),
    bearman: require('./assets/images/drivers/bearman.png'),
    bottas: require('./assets/images/drivers/bottas.png'),
    gasly: require('./assets/images/drivers/gasly.png'),
    hamilton: require('./assets/images/drivers/hamilton.png'),
    hulkenberg: require('./assets/images/drivers/hulkenberg.png'),
    kevin_magnussen: require('./assets/images/drivers/kevin_magnussen.png'),
    leclerc: require('./assets/images/drivers/leclerc.png'),
    max_verstappen: require('./assets/images/drivers/max_verstappen.png'),
    norris: require('./assets/images/drivers/norris.png'),
    ocon: require('./assets/images/drivers/ocon.png'),
    perez: require('./assets/images/drivers/perez.png'),
    piastri: require('./assets/images/drivers/piastri.png'),
    ricciardo: require('./assets/images/drivers/ricciardo.png'),
    russell: require('./assets/images/drivers/russell.png'),
    sainz: require('./assets/images/drivers/sainz.png'),
    sargeant: require('./assets/images/drivers/sargeant.png'),
    stroll: require('./assets/images/drivers/stroll.png'),
    tsunoda: require('./assets/images/drivers/tsunoda.png'),
    zhou: require('./assets/images/drivers/zhou.png'),
}

export const constructorCars = {
    aston_martin: require('./assets/images/cars/aston-martin.png'),
    ferrari: require('./assets/images/cars/ferrari.png'),
    mercedes: require('./assets/images/cars/mercedes.png'),
    alpine: require('./assets/images/cars/alpine.png'),
    haas: require('./assets/images/cars/haas.png'),
    mclaren: require('./assets/images/cars/mclaren.png'),
    rb: require('./assets/images/cars/rb.png'),
    red_bull: require('./assets/images/cars/red-bull-racing.png'),
    sauber: require('./assets/images/cars/kick-sauber.png'),
    williams: require('./assets/images/cars/williams.png'),
};